services:
  pr-frontend:
    build: ./frontend
    image: patientrecords-frontend
    container_name: patientrecords-frontend
    ports:
      - "8081:80"
    networks:
      - app-net
  pr-backend:
    build: ./backend
    image: patientrecords-backend
    container_name: patientrecords-backend
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/patientrecords?authSource=admin
    ports:
      - "5001:5001"
    volumes:
      - ../POC-ccnc/data:/data:ro
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-net
  mongo:
    build: ./mongo
    image: patientrecords-mongodb
    container_name: patientrecords-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "admin", "-p", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net
volumes:
  mongo_data:
    driver: local

networks:
  app-net:
    driver: bridge
